#markdown: rdiscount
markdown: kramdown
permalink: /:year/:month/:day/:title.html
url: http://siyangliu.github.io/
name: "SiyangLiu"
author: "SiyangLiu"
highlighter: pygments
safe: true
paginate: 16
auto: true
